services:
  bff:
    build:
      context: ./client/bff
    environment:
      AFFILIATES_API_URL: http://affiliates:8000
      LOYALTY_API_URL: http://loyalty:8010
      DEBUG: "true"
    depends_on:
      - affiliates
      - loyalty
    ports: ["8080:8080"]  

  mq:
      image: rabbitmq:3-management
      ports:
        - "5672:5672"   # broker
        - "15672:15672" # mgmt UI
      healthcheck:
        test: ["CMD", "rabbitmq-diagnostics", "check_running"]
        interval: 5s
        timeout: 3s
        retries: 20

  affiliates_db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports: ["5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d app"]
      interval: 5s
      timeout: 3s
      retries: 20  

  affiliates:
    build:
      context: ./affiliates
      dockerfile: Dockerfile.api 
    environment:
      DATABASE_URL: postgresql+psycopg2://app:app@affiliates_db:5432/app
      BROKER_URL: amqp://guest:guest@mq:5672//
      DEBUG: "true"
    depends_on:
      affiliates_db:
        condition: service_healthy
      mq:
        condition: service_healthy
    ports: ["8000:8000"]

  affiliates_worker:
    build: 
      context: ./affiliates
      dockerfile: Dockerfile.worker
    environment:
      DATABASE_URL: postgresql+psycopg2://app:app@affiliates_db:5432/app
      BROKER_URL: amqp://guest:guest@mq:5672//
    depends_on:
      affiliates_db:
        condition: service_healthy
      mq:
        condition: service_healthy

  loyalty_db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports: ["5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d app"]
      interval: 5s
      timeout: 3s
      retries: 20  

  loyalty:
    build:
      context: ./loyalty
    environment:
      DATABASE_URL: postgresql+psycopg2://app:app@loyalty_db:5432/app
      BROKER_URL: amqp://guest:guest@mq:5672//
      DEBUG: "true"
    depends_on:
      affiliates_db:
        condition: service_healthy
      mq:
        condition: service_healthy
    ports: ["8010:8010"]

        
