services:
  pulsar:
    image: apachepulsar/pulsar:3.2.0
    command: ["bash","-c","bin/pulsar standalone --no-functions-worker"]
    ports: ["6650:6650", "8090:8090"]
    environment:
      PULSAR_PREFIX_advertisedAddress: pulsar 
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8090/admin/v2/brokers/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 15s
  
  bff:
    build:
      context: ./client/bff
    environment:
      PULSAR_URL: pulsar://pulsar:6650
      AFFILIATES_API_URL: http://affiliates:8000
      TOPIC_COMMANDS_AFFILIATES: commands.affiliates
      # LOYALTY_API_URL: http://loyalty:8010
      ALLIANCES_API_URL: http://alliances:8020
      TOPIC_COMMANDS_ALLIANCES: commands.alliances
      DEBUG: "true"
    depends_on:
      pulsar:
        condition: service_healthy
    ports: ["8080:8080"]

  affiliates_db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports: ["5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d app"]
      interval: 5s
      timeout: 3s
      retries: 20  

  affiliates:
    build:
      context: ./affiliates
    environment:
      DATABASE_URL: postgresql+psycopg2://app:app@affiliates_db:5432/app
      BROKER_URL: amqp://guest:guest@mq:5672//
      DEBUG: "true"
    depends_on:
      affiliates_db:
        condition: service_healthy
      pulsar:
        condition: service_healthy
    ports: ["8000:8000"]

  affiliates_worker:
    build: 
      context: ./affiliates
    environment:
      DATABASE_URL: postgresql+psycopg2://app:app@affiliates_db:5432/app
      PULSAR_URL: pulsar://pulsar:6650
      TOPIC_COMMANDS_AFFILIATES: commands.affiliates
      SUBSCRIPTION_NAME: affiliates-svc
    depends_on:
      affiliates_db:
        condition: service_healthy
      pulsar:
        condition: service_healthy
    command: python -m presentation.worker

  # loyalty_db:
  #   image: postgres:16
  #   environment:
  #     POSTGRES_USER: app
  #     POSTGRES_PASSWORD: app
  #     POSTGRES_DB: app
  #   ports: ["5432"]
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U app -d app"]
  #     interval: 5s
  #     timeout: 3s
  #     retries: 20  

  # loyalty:
  #   build:
  #     context: ./loyalty
  #   environment:
  #     DATABASE_URL: postgresql+psycopg2://app:app@loyalty_db:5432/app
  #     BROKER_URL: amqp://guest:guest@mq:5672//
  #     DEBUG: "true"
  #   depends_on:
  #     affiliates_db:
  #       condition: service_healthy
  #     mq:
  #       condition: service_healthy
  #   ports: ["8010:8010"]

  alliances:
    build:
      context: ./alliances
    environment:
      DATABASE_URL: postgresql+psycopg2://app:app@alliances_db:5432/app
      BROKER_URL: amqp://guest:guest@mq:5672//
      DEBUG: "true"
    depends_on:
      alliances_db:
        condition: service_healthy
    ports: ["8020:8020"]

  alliances_db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports: ["5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d app"]
      interval: 5s
      timeout: 3s
      retries: 20

  alliances_worker:
    build: 
      context: ./alliances
    environment:
      DATABASE_URL: postgresql+psycopg2://app:app@alliances_db:5432/app
      PULSAR_URL: pulsar://pulsar:6650
      TOPIC_COMMANDS_ALLIANCES: commands.alliances
      SUBSCRIPTION_NAME: alliances-svc
    depends_on:
      alliances_db:
        condition: service_healthy
      pulsar:
        condition: service_healthy
    command: python -m presentation.worker
