services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d app"]
      interval: 5s
      timeout: 3s
      retries: 20

  mq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # broker
      - "15672:15672" # mgmt UI
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 5s
      timeout: 3s
      retries: 20

  afiliates:
    build: .
    environment:
      DATABASE_URL: postgresql+psycopg2://app:app@db:5432/app
      BROKER_URL: amqp://guest:guest@mq:5672//
      DEBUG: "true"
    depends_on:
      db:
        condition: service_healthy
      mq:
        condition: service_healthy
    ports: ["8000:8000"]

  worker:
    build: .
    command: celery -A afiliates.infrastructure.celery_app.celery worker -Q commands -l info
    environment:
      DATABASE_URL: postgresql+psycopg2://app:app@db:5432/app
      BROKER_URL: amqp://guest:guest@mq:5672//
    depends_on:
      db:
        condition: service_healthy
      mq:
        condition: service_healthy
