apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff
  namespace: alpes-experiment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff
  template:
    metadata:
      labels:
        app: bff
    spec:
      containers:
      - name: bff
        image: gcr.io/alpes-experiment/bff:latest
        ports:
        - containerPort: 8080
        env:
        - name: PULSAR_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PULSAR_URL
        - name: AFFILIATES_API_URL
          value: "http://affiliates:8000"
        - name: TOPIC_COMMANDS_AFFILIATES
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: TOPIC_COMMANDS_AFFILIATES
        - name: TRACKING_API_URL
          value: "http://tracking:8010"
        - name: TOPIC_COMMANDS_TRACKING
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: TOPIC_COMMANDS_TRACKING
        - name: ALLIANCES_API_URL
          value: "http://alliances:8020"
        - name: TOPIC_COMMANDS_ALLIANCES
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: TOPIC_COMMANDS_ALLIANCES
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DEBUG
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: bff
  namespace: alpes-experiment
spec:
  selector:
    app: bff
  ports:
  - port: 8080
    targetPort: 8080
  type: NodePort
