apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bff-ingress
  namespace: alpes-experiment
  annotations:
    kubernetes.io/ingress.class: "gce"
    networking.gke.io/managed-certificates: "bff-ssl-cert"
    cloud.google.com/backend-config: '{"default": "bff-backend-config"}'
spec:
  rules:
  - http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: bff
            port:
              number: 8080
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: bff-backend-config
  namespace: alpes-experiment
spec:
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3
    type: HTTP
    requestPath: /health
    port: 8080
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: bff-ssl-cert
  namespace: alpes-experiment
spec:
  domains:
    - bff-alpes-experiment.example.com
