FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.worker.txt constraints.txt ./
RUN pip install --no-cache-dir -r requirements.worker.txt

COPY . .

ENV PYTHONPATH=/app

CMD ["celery", "-A", "infrastructure.celery_app.celery", "worker", "-Q", "commands, events", "-l", "info"]
